name: backend-CICD

on:
  workflow_call:

env:
  docker_image_name: ${{ github.event.repository.name }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: gradle build
      run: |
        gradle build -x test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: feltpen/live:${{ env.docker_image_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          "DB_HOST=${{ secrets.DB_HOST }}"
          "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          "DB_USERNAME=${{ secrets.DB_USERNAME }}"
          "DEFAULT_DATABASE=${{ secrets.DEFAULT_DATABASE }}"
          "SMTP_EMAIL=${{ secrets.SMTP_EMAIL }}"
          "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"
  
